### ISSUE TITLE
inputRef no longer working

### ISSUE THREAD

**Issue by dcporter44** [Andarist/react-textarea-autosize#254]
I'm on version 7.0 of this library and using React 16.9.

Passing the inputRef prop to TextareaAutosize does not do anything and I receive this console error: 
"React does not recognize the `inputRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputref` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

I'm not doing anything else interesting.
`<TextareaAutosize value="some text" onChange={this.handleChange} inputRef={ref => this.input = ref}/>`

**Comment by dcporter44** [comment]
Found a workaround:

`
<TextareaAutosize value="some text" onChange={this.handleChange} ref={this.inputRef}/>
`

**Comment by dcporter44** [comment]
Accidentally hit Close button

**Comment by Andarist** [comment]
That's weird - `inputRef` is being removed from props which are getting passed down to a host component here:
https://github.com/andreypopp/react-textarea-autosize/blob/6bc1574944857bc8fac58513219ffcdebf3a49cf/src/index.js#L46-L54

So it definitely shouldn't land on the DOM.

Additionally, callback refs are supported for quite a long time, this is the ref which we pass to React:
https://github.com/andreypopp/react-textarea-autosize/blob/6bc1574944857bc8fac58513219ffcdebf3a49cf/src/index.js#L102-L112

Could you prepare a repro case for what you are experiencing?

**Comment by Andarist** [comment]
I've released the new major version which uses `forwardRef` under the hood so you should be able to just use `ref` prop now.

**Comment by orzarchi** [comment]
@Andarist the NPM page docs are outdated and still show the old prop name

**Comment by Andarist** [comment]
This will get fixed in the upcoming release which should get released in a couple of days.
